// <auto-generated />
using System;
using BibliothequeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliothequeAPI.Migrations
{
    [DbContext(typeof(BibliothequeContext))]
    [Migration("20260414094936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliothequeAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnneePublication")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DOI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domaine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("LienAcces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotsCles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Resume")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Revue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneePublication = 2023,
                            Auteur = "Dr. Ahmed Ben Ali",
                            DateAjout = new DateTime(2026, 4, 14, 9, 49, 36, 440, DateTimeKind.Utc).AddTicks(5678),
                            Domaine = "Intelligence Artificielle",
                            EstActif = true,
                            MotsCles = "ML, Deep Learning, Neural Networks",
                            Resume = "Une introduction complète aux techniques d'apprentissage automatique.",
                            Revue = "Journal of AI Research",
                            Titre = "Introduction au Machine Learning"
                        },
                        new
                        {
                            Id = 2,
                            AnneePublication = 2023,
                            Auteur = "Dr. Sophie Laurent",
                            DateAjout = new DateTime(2026, 4, 14, 9, 49, 36, 440, DateTimeKind.Utc).AddTicks(6684),
                            Domaine = "Architecture Logicielle",
                            EstActif = true,
                            MotsCles = "Microservices, Docker, Kubernetes",
                            Resume = "Analyse des architectures microservices modernes.",
                            Revue = "IEEE Software",
                            Titre = "Microservices Architecture"
                        });
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Emprunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReelle")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PenaliteRetard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnneePublication")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Editeur")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int>("ExemplairesDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageCouverture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreExemplaires")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Livres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneePublication = 1943,
                            Auteur = "Antoine de Saint-Exupéry",
                            Categorie = "Littérature",
                            DateAjout = new DateTime(2026, 4, 14, 9, 49, 36, 439, DateTimeKind.Utc).AddTicks(8785),
                            Description = "Un chef-d'œuvre de la littérature mondiale.",
                            EstActif = true,
                            ExemplairesDisponibles = 3,
                            Genre = "Roman",
                            ISBN = "9782070612758",
                            NombreExemplaires = 3,
                            Titre = "Le Petit Prince"
                        },
                        new
                        {
                            Id = 2,
                            AnneePublication = 2008,
                            Auteur = "Robert C. Martin",
                            Categorie = "Développement",
                            DateAjout = new DateTime(2026, 4, 14, 9, 49, 36, 440, DateTimeKind.Utc).AddTicks(227),
                            Description = "Guide de bonnes pratiques en développement logiciel.",
                            EstActif = true,
                            ExemplairesDisponibles = 2,
                            Genre = "Informatique",
                            ISBN = "9780132350884",
                            NombreExemplaires = 2,
                            Titre = "Clean Code"
                        },
                        new
                        {
                            Id = 3,
                            AnneePublication = 1994,
                            Auteur = "Gang of Four",
                            Categorie = "Architecture",
                            DateAjout = new DateTime(2026, 4, 14, 9, 49, 36, 440, DateTimeKind.Utc).AddTicks(230),
                            Description = "Les patrons de conception incontournables.",
                            EstActif = true,
                            ExemplairesDisponibles = 2,
                            Genre = "Informatique",
                            ISBN = "9780201633610",
                            NombreExemplaires = 2,
                            Titre = "Design Patterns"
                        });
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateInscription = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@biblio.com",
                            EstActif = true,
                            Nom = "Admin",
                            Prenom = "Bibliothèque",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DateInscription = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.dupont@mail.com",
                            EstActif = true,
                            Nom = "Dupont",
                            Prenom = "Marie",
                            Role = "Membre"
                        },
                        new
                        {
                            Id = 3,
                            DateInscription = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.martin@mail.com",
                            EstActif = true,
                            Nom = "Martin",
                            Prenom = "Jean",
                            Role = "Membre"
                        });
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Emprunt", b =>
                {
                    b.HasOne("BibliothequeAPI.Models.Livre", "Livre")
                        .WithMany("Emprunts")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliothequeAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany("Emprunts")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Livre", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("BibliothequeAPI.Models.Utilisateur", b =>
                {
                    b.Navigation("Emprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
